### PR TITLE
Fixed bug with duplicate of items in menu.

### LINKED ISSUE #7: Small bug, if cancelling the set-API-key dialog, the option get's added again
A picture is worth a thousand words:

### PR DESCRIPTION
**Pull request by 2Grey**
This commit resolved #7

### CODE REVIEW

File: WakaLet/NSMenuItem+Equal.m [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+{
+    if ([self.title isEqualToString:checkItem.title]
+        && [NSStringFromSelector(self.action) isEqualToString:NSStringFromSelector(checkItem.action)]
+        && [self.keyEquivalent isEqualToString:checkItem.keyEquivalent])
+    {
+        return YES;
+    }
+    return NO;
+}
+
```
Comment (jontelang) [inline WakaLet/NSMenuItem+Equal.m:23]: I guess this would break in case you would want multiple same buttons on different locations within the menu. Not really a problem in this case though.

**Comment by jontelang** [comment]
Merging, thanks bug-reporter and fixer!
EDIT: Fixing merge conflict first though.
